language: swift
osx_image: xcode11
xcode_project: r2-navigator-swift.xcodeproj
xcode_scheme: r2-navigator-swift
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_sdk: iphonesimulator13.0

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild clean build -quiet

